apiVersion: v1          # 쿠버네티스 코어 API 버전
kind: ConfigMap        # 생성할 리소스의 종류: 환경설정 데이터를 저장하는 ConfigMap
metadata:
  name: hailey-community-config-backend    # 이 ConfigMap의 고유 이름 (백엔드용)
                                           # Helm 템플릿 문법: 배포 시 지정된 네임스페이스를 동적으로 주입
  namespace: {{ .Release.Namespace }}
  labels: # 리소스를 분류하고 관리하기 위한 꼬리표
    app: hailey-community
    tier: backend
data: # 백엔드(Spring Boot) 컨테이너에 주입될 환경 변수 데이터 (Key-Value)
  # values.yaml에서 스프링 부트 실행 환경(예: "prod", "dev")을 가져와 문자열로 주입
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.config.springProfilesActive | quote }}


  # values.yaml에서 백엔드 서버가 뜰 포트 번호(예: "8090")를 가져와 문자열로 주입
  SERVER_PORT: {{ .Values.backend.config.serverPort | quote }}

  # values.yaml에서 프론트엔드의 접근을 허용할 주소(CORS 설정)를 가져와 문자열로 주입
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.config.corsAllowedOrigins | quote }}
