apiVersion: v1 # 쿠버네티스 코어 API 버전
kind: Service # 생성할 리소스의 종류: 파드(Pod)들에게 고정된 IP와 네트워크 길을 열어주는 Service
metadata:
  name: frontend-service # 이 서비스의 고유 이름
  # Helm 템플릿 문법: 배포 시 지정된 네임스페이스를 동적으로 주입
  namespace: {{ .Release.Namespace }}
  labels: # 이 '서비스 리소스 자체'에 붙이는 꼬리표
    app: hailey-community
    tier: frontend
spec: # 서비스의 구체적인 네트워크 동작 방식 명세
  # values.yaml에서 서비스 타입(예: ClusterIP)을 가져와 주입
  type: {{ .Values.frontend.service.type }}

  selector: # [중요] 어떤 파드(Pod)들에게 트래픽을 전달할지 찾는 조건
    app: hailey-community # 이 라벨을 가지고 있고,
    tier: frontend        # 이 라벨도 가지고 있는 파드를 찾아서 연결해라!

  ports: # 포트 설정 (어떤 포트로 들어와서 컨테이너의 어디로 보낼지)
    - name: http # 이 포트 규칙의 이름
      protocol: TCP # 웹 통신이므로 TCP 프로토콜 사용
      # 이 서비스(frontend-service)가 외부/내부에 개방할 포트 번호 (values.yaml 참조)
      port: {{ .Values.frontend.service.port }}
      # 최종적으로 트래픽을 전달받을 실제 파드(컨테이너)의 포트 번호나 이름
      targetPort: http
